<header>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" style="font-size: 30px;" href="#">MyWallet
                <span style="color: #f79300;"> <i class="fa-solid fa-wallet"></i></span>
            </a>

            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="">Sign In <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="signUp">Sign up</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main>
    <div class="container d-flex justify-content-center">
        <div class="form-container">
            <img class="d-block mx-auto mb-5" src="imgs/perfil.png" alt="">
            <form method="POST" action="auth" id="login-form">
                <div class="form-group">
                    <i class="fa-solid fa-envelope"></i>
                    <input type="email" placeholder=" " id="email" name="email" required>
                    <label for="email">Email</label>
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                </div>
                <div class="form-group">
                    <i class="fa-solid fa-lock"></i>
                    <input type="password" id="pass" name="pass" required>
                    <label for="pass">Password</label>
                </div>
                <div class="form-group">

                    <!-- <p style="color: red;">User invalid!</p> -->

                </div>
                <div class="form-check mb-3">
                    <input type="checkbox" class="form-check-input" id="remenber" name="remenber">
                    <label class="form-check-label" for="remenber">Remenber me</label>
                </div>

                <button type="submit" class="btn">Sign in</button>
            </form>
        </div>
    </div>
</main>