
    <script src="../js/signUp.js"></script>

    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" style="font-size: 30px;" href="#">MyWallet
                    <span style="color: #f79300;"> <i class="fa-solid fa-wallet"></i></span>
                </a>

                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="/">Sign In <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="signUp">Sign up</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

<main>
        <div class="container d-flex justify-content-center">
            <div class="form-container">
                <img class="d-block mx-auto mb-5" src="imgs/perfil.png" alt="">
                <form method="POST" id="login-form">
                    <div class="form-group">
                        <i class="fa-solid fa-user"></i>
                        <input type="text" id="username" name="username" required>
                        <label for="email">Nome</label>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-envelope"></i>
                        <input type="email" id="email" name="email" placeholder=" " required>
                        <label for="email">Email</label>

                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-lock"></i>
                        <input type="password" id="pass" name="pass" required>
                        <label for="pass">Password</label>
                        <small class="form-text text-muted">Never share your password with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-lock"></i>
                        <input type="password" id="confirm_pass" required>
                        <label for="pass">Confirm your Password</label>
                        <small class="form-text text-muted">Type the same password you typed above.</small>
                    </div>

                    <p id="alert" style="color:#c68d20;"></p>

                    <button type="submit" class="btn">Sign up</button>
                </form>
            </div>
        </div>
    </main>